apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
  namespace: blockchain
type: Opaque
stringData:
  password: "dev_password_123"
  # TODO: Migrer vers Sealed Secrets après validation dans l'env talos
